FROM alpine:latest

MAINTAINER <shenqinpeng@126.com>

RUN apk update && \
    apk add --no-cache nginx curl tzdata && \
    cp -rf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    mkdir -p /run/nginx && touch /run/nginx/nginx.pid

EXPOSE 80 443

STOPSIGNAL SIGTERM

HEALTHCHECK --interval=5m --timeout=3s CMD curl -f http://localhost/ || exit 1

CMD ["/usr/sbin/nginx", "-g", "daemon off;"]
