FROM alpine:latest

MAINTAINER <shenqinpeng@126.com>

RUN apk update && \
    apk add --no-cache nginx curl tzdata && \
    cp -rf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    mkdir -p /run/nginx && touch /run/nginx/nginx.pid
    
RUN echo """
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /home;
        index index.html index.htm;

        # Everything is a 404
        #location /tmp {

        #       return 404;
        #}

        # You may need this to prevent return 404 recursion.
        location = /404.html {
                internal;
        }
}
""" > /etc/nginx/conf.d/default.conf && echo "test scp" > /home/index.html

EXPOSE 80 443

STOPSIGNAL SIGTERM

HEALTHCHECK --interval=5m --timeout=3s i--retries=3 CMD curl -f http://localhost || exit 1

CMD ["/usr/sbin/nginx", "-g", "daemon off;"]
